name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test
  build-publish-wasm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates: [engine, common-ui]
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and pack wasm
        run: |
          wasm-pack build \
            --scope '${{ github.repository_owner }}' \
            --target web \
            'crates/${{ matrix.crates }}' \
            --features wasm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Publish npm package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd 'crates/${{ matrix.crates }}/pkg'
          # no option to customize publish config in wasm-pack
          SHA_7="$(expr substr $GITHUB_SHA 1 7)"
          VERSION="$(jq -r '.version' package.json)"
          REGISTRY='{"publishConfig":{"registry":"https://npm.pkg.github.com"}}'
          echo "$(jq ". |= . + $REGISTRY" package.json)" > package.json
          cat package.json | jq
          npm version "${VERSION}-git.${SHA_7}"
          cat package.json | jq
          npm publish
  build-publish-frontend:
    runs-on: ubuntu-latest
    needs: [build-publish-wasm]
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd frontend
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' >> .npmrc
          npm install
          npm run build
      - name: Deploy artifacts
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
